# Generated by Django 4.2.3 on 2023-09-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_email_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=2, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
