# Generated by Django 4.2.3 on 2023-09-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
        ('users', '0008_alter_profile_phone_number'),
    ]

    operations = [
    ]
