# Generated by Django 4.2.3 on 2023-09-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_remove_advertising_image_remove_advertising_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
