# Generated by Django 4.2.3 on 2023-09-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryReservation',
        ),
    ]
