# Generated by Django 4.2.3 on 2023-09-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_housingreservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingreservation',
            name='adults',
            field=models.PositiveIntegerField(default=1, verbose_name='Взрослые(от 18 лет)'),
        ),
        migrations.AddField(
            model_name='housingreservation',
            name='children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Дети(от 2-12 лет)'),
        ),
    ]
