# Generated by Django 4.2.3 on 2023-09-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_housingavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingavailability',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='housingavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='housingavailability',
            name='housing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='travel.housing', verbose_name='Место жительства'),
            preserve_default=False,
        ),
    ]
